export const BEADS_PER_MALA = 108;

export const BELL_SOUND_URL = "https://cdn.freesound.org/previews/339/339810_5121236-lq.mp3"; // Public domain bell sound

export const TRANSLATIONS = {
  en: {
    appTitle: "ABHi Jap Mala",
    addMantra: "Add New Mantra",
    enterMantraPlaceholder: "Om Namah Shivaya...",
    startChanting: "Start Chanting",
    beads: "Beads",
    malas: "Malas",
    today: "Today",
    lifetime: "Lifetime",
    reset: "Reset",
    settings: "Settings",
    sound: "Bell Sound",
    language: "Language",
    delete: "Delete",
    back: "Back",
    cancel: "Cancel",
    save: "Save",
    completed: "Mala Completed!",
    selectToChant: "Select a mantra to begin",
    noMantras: "No mantras added yet. Tap '+' to add one.",
    hindi: "Hindi",
    english: "English",
    confirmDelete: "Are you sure you want to delete this mantra?",
    todayMalasLabel: "Todays malas",
    lifetimeMalasLabel: "Lifetime malas",
    naam: "naam",
    about: "About & Help",
    developedBy: "Developed By",
    developerName: "Abhishek Alli",
    rightsReserved: "All rights reserved.",
    howToUseTitle: "How to Use",
    howToUseSteps: [
      "Tap the '+' button to add a new Mantra.",
      "Select a Mantra from the list to start chanting.",
      "Tap anywhere on the screen (or the circle) to count a bead.",
      "The counter resets to 1 after 108 beads (1 Mala).",
      "Use the bottom-center back button to undo a count.",
      "Daily counts reset automatically at midnight."
    ]
  },
  hi: {
    appTitle: "ABHi जप माला",
    addMantra: "नया मंत्र जोड़ें",
    enterMantraPlaceholder: "ॐ नमः शिवाय...",
    startChanting: "जप प्रारंभ करें",
    beads: "मनके",
    malas: "माला",
    today: "आज",
    lifetime: "जीवनकाल",
    reset: "रीसेट",
    settings: "सेटिंग्स",
    sound: "घंटी की ध्वनि",
    language: "भाषा",
    delete: "हटाएं",
    back: "वापस",
    cancel: "रद्द करें",
    save: "सहेजें",
    completed: "माला पूर्ण हुई!",
    selectToChant: "शुरू करने के लिए एक मंत्र चुनें",
    noMantras: "अभी तक कोई मंत्र नहीं जोड़ा गया है। जोड़ने के लिए '+' दबाएं।",
    hindi: "हिंदी",
    english: "अंग्रेजी",
    confirmDelete: "क्या आप वाकई इस मंत्र को हटाना चाहते हैं?",
    todayMalasLabel: "आज की माला",
    lifetimeMalasLabel: "कुल माला",
    naam: "नाम",
    about: "परिचय और सहायता",
    developedBy: "डेवलपर",
    developerName: "अभिषेक अल्ली",
    rightsReserved: "सर्वाधिकार सुरक्षित।",
    howToUseTitle: "उपयोग कैसे करें",
    howToUseSteps: [
      "नया मंत्र जोड़ने के लिए '+' बटन दबाएं।",
      "जप शुरू करने के लिए सूची से एक मंत्र चुनें।",
      "गिनती के लिए स्क्रीन पर कहीं भी टैप करें।",
      "१०८ मनकों (१ माला) के बाद काउंटर १ पर रीसेट हो जाता है।",
      "गिनती वापस लेने के लिए नीचे दिए गए बटन का उपयोग करें।",
      "दैनिक गिनती आधी रात को अपने आप रीसेट हो जाती है।"
    ]
  }
};